from multiprocessing.resource_sharer import stop
import os
import time
import sys

def cartao():
    print("MMXx;...............................................................................................................................................................................,lONMMMM ")
    print("Nk;.....................................................................................................................................................................................;dXMM")
    print("o.........................................................................................................................................................................................,kN")
    print("..............;lxOOO0kdc'...,lxOx,......................................................................................................................................... .;c::'...........")
    print("...........;lxOko:',cdO0ko:,;loc,.......................................................................................................................................... ,x0OOc...........")
    print("........,lxO0OOd,....';cdOOko:'....................................................................................    ......................... .......................... 'x0OOc...........")
    print("......:xOOOOOOOkl'.;lxx:.,oOOOko'.......................................;xxxxx;......xxxxx. .xxxx,...xxxx''xx....xxxxxxx'.......xxxxxxx......xxxxxxx:,.....,xxx''xx...,xxx:,;x0OOc...........")
    print(".......;lxO0koc;:lxOOo:;:lxOOdc,......................................'okOOdok0Ox:. .o0O0d. .d0O0d. .d0OOxk0k;.cxOOxoxO0ko'...ckOOxoxO0kl'..lkO0xlok0Od,. 'x0OOxk0k,.ckO0koodOOOOc...........")
    print("..........;:;:lxOOdc;:lxOOdc,.........................................o0OOl..;kOOk; .o0O0d. .o0O0d. .d0O0ko:,.:OOOx, .oOOOo..cOO0x,.'okkkc.'cllc'..o0OOo. 'x0OOkl;,.;k0OO:..cOOOOc...........")
    print("..........,lxOOdc;;lxOOdc;;:'........................................,kOOO:. 'x0OOc..o0O0d. .o0O0d. .d0O0o.  .o0O0o. .cOO0x'.o0O0o. ..'''....:cooodkOO0o. 'x0O0o. ..:OO0k,..,k0OOc...........")
    print(".......,lxOOdc;;cxOOdc;;cxOOkdc'.....................................,k0OO:. 'x0OOl..o0O0d. .o0O0d. .d0O0l.. .o0O0o. .cOO0x'.d0O0o. .......;xO0kl,;dOO0o. 'x0OOl....:OO0k,..,k0OOc...........")
    print("......:xOOOx:.'lxdc,.;dOOOOOOOOo'................................... 'x0OOc. 'x0OO:..o0O0d. .d0O0d. .d0O0l....cOO0d. .lOO0d..oOO0d. .cddd;.o0O0d. .o0O0o. 'x0OOl....;k0Ok;..;kOOOc...........")
    print("........;lxOOxl:,.....ckOOOkdc'.......................................:kO0xc:oO0Oo. .cOOOkl:lkOO0d. .d0O0l....'dO0Oo:lkOOx;..,dO0kl:lk0Od,.cOOOkl:lkOO0d. 'x0OOl... .oOOOd::dOOOOc...........")
    print("......,cl:,;lxOOxl;',lxOkd:'...........................................'cldxxdol;.....:odddl;cooo:. .:olo:......;loddddl:'.....:lodddol:....;ldddl;;looc. .cooo;......:odddl:cooo;...........")
    print(".....:OOxl'...;lxOOkOOdc'....................................................................................................................................................................")
    print(".....;l;.........;loc'.......................................................................................................................................................................")
    print(".............................................................................................................................................................................................")
    print("...............;cloooodddddoodxxkkkkkddkOO0000000Oo'.........................................................................................................................................")
    print("..............;oddddxxxxxkkkkxxkO0OkkOKKKKKXXXXXXXXd.........................................................................................................................................")
    print("..............:ddxxxxkkkkOOOOOkxO0kkKKKKXXXXXXXXXNNk'.........................'dx,...........................................................................................................")
    print("..............:xxxkkkkOOOO0000kx0KkOXXXXXXXXXNNNNNNk'......................ox;.;kx'..........................................................................................................")
    print("..............:ddxxxxxkkkkkkkkO0KK0KX0OO00000000000d'...............'..lx:.,kk,.cOl..........................................................................................................")
    print("..............:xkkkkOOOOO00kkKKXXXXXXOkKKKKKKKK000Od'..............;xo.,xk,.cOl.'xk, ........................................................................................................")
    print("..............ckOO0000KKKKXOkKXXXXXXXOONNNNXXXKK000d' ..............oO:.cOc.,kd..dO;.........................................................................................................")
    print("..............cO000KKKKKKXXOkKXXXXXNXOONNXXKK000OOOo'...............oO:.lOc.,kd..dO;.........................................................................................................")
    print("..............ckOOO00000000kkKXNNNNNXkk000OOOkkkkxxo'..............;xl.,xk,.cOl.'kx' ........................................................................................................")
    print("..............cOOOOO0000000000OKNNKOOOkOkkkxxxxxdddl. .................cd;.;kx,.lOl. ........................................................................................................")
    print("..............lKXXXXXXXXNNNNNN0kKKkkK00OOOOkkkxxxxxl'......................ld,.:kx,..........................................................................................................")
    print("..............lKXXXXXXXNNNNNNXOk00kxOOOkkkkkxxxxdddl'..........................od;...........................................................................................................")
    print("..............:OXXXXNNNNNNXK0kkO00Oxdxkkxxxxxddddddc. .......................................................................................................................................")
    print("...............;dkOOOOOOkkkdodxxddddollooooolllllc;..........................................................................................................................................")
    print(".,cxOl.......................................................................................................................................................................................")
    print("xOKK0l.......................................................................................................................................................................................")
    print("KK0K0l..........................................................................................................................................................''...........................")
    print("KK0K0l.................................................................................................................,;:cccccc:'.......;cccl;..;ccll,....,;:cllllll:.......,cccclc.........")
    print("KK0K0l.....................................................................................................................,clccoc......;clclc..'clcll' .,clllcccccco:......;clllclo,........")
    print("KK0K0l......................................................................................................................,cllll.....,clllc...;llll;..,clll:'.....,......,cllcllll;........")
    print("KK0K0l.......................................................................................................................;llll'....clll:....:lll:...;llll:'...........'cllc,:llo:........")
    print("KK0K0l.......................................................................................................................'lddo;...cdddc....;dxxd;...'lxxxxdoc;.......'okkd;.,dkkd'.......")
    print("KK0K0l........................................................................................................................l0KKd..oKKKk,....dKKXx'.....;okKXXXKOl.....xXNXo...xNNXl.......")
    print("KK0K0l.....................................................................'..................................................;KWWKclXWWXc....:KWWNo.........;dKWWWNd...dNWWKc,,,xNWWO,......")
    print("KK0K0l..........;''l;..;,.;:;;;,....::',;,.....,;',;.':..;,,,;..;,. ';';c,,,..:................................................xNNNKXNNXd.....dXNNK:...........oXXXNx..lKXXXKK000KXXXKo......")
    print("KK0K0l........ .c',oc;'c;;c...,l;. .cc''c;.....;:,,;.,c'::. .;c':;. 'l;cl,''..c................................................:k000000x'....,x0O0x' .;ddlccccoxOOOk:.;xOOOxooooooxkkOx,.....")
    print("KK0K0l.........,l',c.,lo;;l,..'c,...cc''.......,'.;l,,c';:..'::.::..;c'co,''..c.................................................lkkkkkd,.....cxkxkc...cxkkkkkkkxxoc'.,dkxkd,......;xxxkc.....")
    print("KK0K0l.........;,.',..,l,.,;,,;'....,'.........,;,,,..,..,,;:c,..;,,;'.,:;;,'.;..................................................,;,,;'......';,,;.....,;;;::;;,'....',,,;'........,,,;,.....")
    print("KK0K0l.......................................................................................................................................................................................")

def limpar():
     os.system('cls')

def aguardar():
    time.sleep(5)

def abertura():
    print("*************************************************************************************************************************************************************************************")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **")
    print("**                                                           ######                                                    ###                                                         **")
    print("**                                                           #     # ###### #    #    #    # # #    # #####   ####     ###                                                         **")
    print("**                                                           #     # #      ##  ##    #    # # ##   # #    # #    #    ###                                                         **")
    print("**                                                           ######  #####  # ## #    #    # # # #  # #    # #    #     #                                                          **")
    print("**                                                           #     # #      #    #    #    # # #  # # #    # #    #                                                                **")
    print("**                                                           #     # #      #    #     #  #  # #   ## #    # #    #    ###                                                         **")
    print("**                                                           ######  ###### #    #      ##   # #    # #####   ####     ###                                                         **")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **")                                                                 
    print("**                                          #                                                                                                                                      **")
    print("**                                         # #    ####     #####  #####   ####   ####  #####    ##   #    #   ##      #####  ######                                                **")
    print("**                                        #   #  #    #    #    # #    # #    # #    # #    #  #  #  ##  ##  #  #     #    # #                                                     **")
    print("**                                       #     # #    #    #    # #    # #    # #      #    # #    # # ## # #    #    #    # #####                                                 **")
    print("**                                       ####### #    #    #####  #####  #    # #  ### #####  ###### #    # ######    #    # #                                                     **")
    print("**                                       #     # #    #    #      #   #  #    # #    # #   #  #    # #    # #    #    #    # #                                                     **")
    print("**                                       #     #  ####     #      #    #  ####   ####  #    # #    # #    # #    #    #####  ######                                                **")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **")                                                                                                                        
    print("**                            ####    ##   #####    ##    ####  ##### #####   ####     #####  ######     ####    ##   #####  #####  ####  ######  ####                             **")
    print("**                           #    #  #  #  #    #  #  #  #        #   #    # #    #    #    # #         #    #  #  #  #    #   #   #    # #      #                                 **")
    print("**                           #      #    # #    # #    #  ####    #   #    # #    #    #    # #####     #      #    # #    #   #   #    # #####   ####                             **")
    print("**                           #      ###### #    # ######      #   #   #####  #    #    #    # #         #      ###### #####    #   #    # #           #                            **")
    print("**                           #    # #    # #    # #    # #    #   #   #   #  #    #    #    # #         #    # #    # #   #    #   #    # #      #    #                            **")
    print("**                            ####  #    # #####  #    #  ####    #   #    #  ####     #####  ######     ####  #    # #    #   #    ####  ######  ####                             **")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **")
    print("**                                                                                                                                                                                 **") 
    print("*************************************************************************************************************************************************************************************")


def opcao():                                                                                                                                                                                                                                                                  
    print("Digite [1] para cadastrar novo cartão")
    print("Digite [2] para consultar cartão")
    print("Digite [3] para excluir cartão")
    print("Digite [4] para substituir cartão cartão\n")
    print("Digite [9] para encerrar o programa\n\n")

def cadastro_cartao():
    print("Digite [1] para cadastrar Visa")
    print("Digite [2] para cadastrar Mastercard")
    print("Digite [3] para cadastrar Elo")
    print("Digite [4] para cadastrar Outros\n")
    print("Digite [9] para encerrar o programa\n\n")

def exclusao_cartao():
    print("Digite [1] para excluir Visa")
    print("Digite [2] para excluir Mastercard")
    print("Digite [3] para excluir Elo")
    print("Digite [4] para excluir Outros\n")
    print("Digite [9] para excluir o programa\n\n")

def substituir_carao():
    print("Digite [1] para substituir Visa")
    print("Digite [2] para substituir Mastercard")
    print("Digite [3] para substituir Elo")
    print("Digite [4] para substituir Outros\n")
    print("Digite [9] para substituir o programa\n\n")


def visa_cartao():
    print("k:::c:::::c::c::::c::::c::c:coONMMMMMMMMMMMMMMMMMMMMMMMMMXdcccccccccccccclOWMMMMW0lclcccccccccccl0WMMMMMMMMMMMMMMMMMWKkol:'..............;cldOXWMMMMMMMMMMMMMMMMMMMMMMMNOdollllllllllllldKMMMMMMMMMMMMMM")
    print("Oc;,..   ......................;dXMMMMMMMMMMMMMMMMMMMMMMNo...............,OWMMMMXc..............'OWMMMMMMMMMMMMMWKxoc;'......................,;l0WMMMMMMMMMMMMMMMMMMMXxc,...............'xWMMMMMMMMMMMMM")
    print("MMMWXOxdl:,......................;0MMMMMMMMMMMMMMMMMMMMWx...............'kWMMMMM0,..............cXMMMMMMMMMMMW0d:'.............................;0MMMMMMMMMMMMMMMMMMMKc.................'.lNMMMMMMMMMMMMM")
    print("MMMMMMMMMWN0xl:'..................cNMMMMMMMMMMMMMMMMMMWO,...............xWMMMMMNo..............'kWMMMMMMMMMNkc'................................lNMMMMMMMMMMMMMMMMMMXc....................;OMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMWKx:................'kMMMMMMMMMMMMMMMMMMK:...............oNMMMMMMK,..............:KMMMMMMMMW0c..................................,OWMMMMMMMMMMMMMMMMMNo'...................'.oWMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMWx................oWMMMMMMMMMMMMMMMMXc...............cXMMMMMMWx'..............xWMMMMMMMNx,...................................:XMMMMMMMMMMMMMMMMMWx'....................'.:0MMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMWl...............:KMMMMMMMMMMMMMMMNd...............:KMMMMMMMK:..............,0MMMMMMMNd'................':coddxxddolc:;'...'xWMMMMMMMMMMMMMMMMWk,......................''dWMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMM0,...............xMMMMMMMMMMMMMMWk'..............;0MMMMMMMWO'..............oNMMMMMMWO,...............:xKWMMMMMMMMMMWWX0kxloXMMMMMMMMMMMMMMMMMO;.......................'.cXMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMWo...............lNMMMMMMMMMMMMW0,..............'kWMMMMMMMXl..............'OMMMMMMMXl...............lXMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMK:............''....'.....'.,kWMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMK;..............,0MMMMMMMMMMMMK:...............xWMMMMMMMM0,..............cXMMMMMWM0,...............dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc............,oc..........''.lNMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMWo...............dWMMMMMMMMMMNl...............oNMMMMMMMMNd..............'kWMMMMMMMO'...............'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.............oXd..........''.:0MMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMK;..............cXMMMMMMMMMWd...............cXMMMMMMMMMK;..............:KMMMMMMMMK:.................,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'..........'.cKWO;..........''.dWMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMWo..............'kMMMMMMMMWO'..............:KMMMMMMMMMWx'..............xWMMMMMMMMWx'...................,cdONMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..........'.,OWMNo..........''.cKMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMK;..............oWMMMMMMW0;..............;0WMMMMMMMMMK:..............,0MMMMMMMMMMNo.......................;lxKWMMMMMMMMMMMMMMMMMMMMMWO;............'dWMMMk,.....'...''.'xWMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMWd..............:KMMMMMMXc..............'kWMMMMMMMMMWO'..............oNMMMMMMMMMMMNk;........................'cd0WMMMMMMMMMMMMMMMMMM0:.............lXMMMMXl..........''.lNMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMK;..............xMMMMMNo...............xWMMMMMMMMMMNl..............'OMMMMMMMMMMMMMMXd,.........................'ckNMMMMMMMMMMMMMMMKc.............:KWMMMMWd.........'''.;OMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMWd..............lNMMMWx...............oNMMMMMMMMMMM0,..............cXMMMMMMMMMMMMMMMWXx:'.........................cOWMMMMMMMMMMMMNo.............,kWMMMMMM0:........'.''.oWMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMX;.............,0MMWO'..............cXMMMMMMMMMMMNd...............kWMMMMMMMMMMMMMMMMMMW0dc,.......................'dNMMMMMMMMMMNd'............'oNMMMMMMMWo......'.''''.:0MMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMWx..............dWWK;..............:KMMMMMMMMMMMMK;..............;0MMMMMMMMMMMMMMMMMMMMMMWKko:,....................'dNMMMMMMMMWk,.............cXMMMMMMMMMO,......''..'''dWMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMX;.............cXXc..............,0MMMMMMMMMMMMWk'..............dWMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl;..................,OWMMMMMMWO;.............;OWMMMMMMMMMXl..'...''.'''.cXMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMWx.............'kd..............'kWMMMMMMMMMMMMX:..............,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc.................dNMMMMMMK:..............:dxxxxxxxxxxxc........''.'.,kMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMX:.............,'..............xWMMMMMMMMMMMMWO'..............oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'...............lNMMMMMKc...............................'....''''''.oNMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMWx............................oNMMMMMMMMMMMMMNl..............'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,...............dNMMMMXo...........................''..'.....''''''.:0MMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMX:..........................cXMMMMMMMMMMMMMM0,..............cKMMMMMMMMNO0XNMMMMMMMMMMMMMMMMMMMMMNd...............,OWMMMNd'................................''...''''''..dWMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMWx.........................:KMMMMMMMMMMMMMMNd...............kWMMMMMMMMO'.;:cdk0XWMMMMMMMMMMMMNKx:................lNMMMWk,................................'''...''''''..cKMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMX:.......................,0MMMMMMMMMMMMMMMK;..............;0MMMMMMMMNo.......',:clodddxxddlc;'.................cKMMMWO;..............................'..'..'..'''''''.'xWMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'.....................'kWMMMMMMMMMMMMMMWk'..............dWMMMMMMMM0,........................................lKWMMM0:..............,:cc::cccccccccccccc:,....''''''''.lNMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:.....................xWMMMMMMMMMMMMMMMX:..............,OMMMMMMMMWx.......................................;xNMMMMKc..............,xNWWWWWWWWWWWWWWWWWWNd'...''''''.'.;OMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'...................oNMMMMMMMMMMMMMMMWO,..............oNMMMMMMMMK:.....................................;dKWMMMMXl...............oNMMMMMMMMMMMMMMMMMMMMK:..''''''''.'.oWMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc..................cXMMMMMMMMMMMMMMMMNl..............'kWMMMMMMMWk'..................................;lkNMMMMMMNd'..............cKMMMMMMMMMMMMMMMMMMMMMWo..''.''''..'.:KMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'................:KMMMMMMMMMMMMMMMMM0,..............cKMMMMMMMMWKdc;,'.........................,:lx0NMMMMMMMMWx'..............,OWMMMMMMMMMMMMMMMMMMMMMMO,............'dWM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOddddddddddddddddKMMMMMMMMMMMMMMMMMMXxdddddddddddddxKWMMMMMMMMMMMWNXK0kxdolc:::;;;;;;:::cldxkOXWMMMMMMMMMMMMNOxxxxxxxxxxxxxxxOWMMMMMMMMMMMMMMMMMMMMMMMNOxxxxxxxxxxxxx0WM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")



def master_cartao():
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OOkkkkkkOO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK0OOkkkkkkOO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdoc;,....           ...',:lox0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc:,'...           ....,;codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;..                               .,:okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:'.                               ..;cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;.                                          .,cxKWMMMMMMMMMMMMMMMMMMMMMWN0d:'.                                          .;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d;.                                                  .,lONMMMMMMMMMMMMMMMWXkc'.                                                  .;d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,.                                                         'lONMMMMMMMMMMXkc.                                                         .,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMXx;.                                                               ,xNMMMMMMNd'                                                               .;xXMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMWKo'                                                                 .;OWMMMMMMNk;                                                                  'oKWMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMW0l.                                                                  ,kNMMXxllxNMMNx,                                                                  .l0WMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMKl.                                                                  .dXMMNx,    ,kNMMXo.                                                                  .lKMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMNd'                                                                   :0WMWO:       .:0WMW0;                                                                   'xNMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMW0;                                                                   .oNMMXo.          .oXMMXo.                                                                   ;0WMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMNd.                                                                   'kWMW0;              ;0WMWk.                                                                   .xNMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMXl.                                                                   ,0WMWx.                'kWMWO,                                                                   .lXMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMK:                                                                    ;0MMNd.                  .dNMM0;                                                                    :KMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMK;                                                                    ,0MMNo.                    .oNMM0,                                                                    ;KMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMK;                                                                    'OMMNo.                      .oNMMO'                                                                    ;KMMMMMMMMMMMM")
    print("MMMMMMMMMMMXc                                                                    .kWMWx.                        .xWMWk.                                                                    cXMMMMMMMMMMM")
    print("MMMMMMMMMMNo                                                                     lNMMO'                          'OMMNl                                                                     oNMMMMMMMMMM")
    print("MMMMMMMMMMk.                                                                     ':::.                            .:::,                                                                     .kMMMMMMMMMM")
    print("MMMMMMMMMX:                                                                                                                                                                                  :XMMMMMMMMM")
    print("MMMMMMMMWx.       ........        ........                                    .:ccc;.                                       .':llolc:'.                                             .:oooo,  .xMMMMMMMMM")
    print("MMMMMMMMX:       c0KKKKKK0;      :OKKKKKK0l                                   oWMMMk.                                    .:xKNMMMMMMMNKd'                                           ;XMMMNl   :NMMMMMMMM")
    print("MMMMMMMMO'      .kMMMMMMMWo     :XMMMMMMMNc     ......             ......    .OMMMNl         ...                       .l0WMMMMMMMMMMMNk'    ......          ..              ...    dWMMM0'   '0MMMMMMMM")
    print("MMMMMMMMx.      :XMMMMMMMMd.   ;KMMMMMMMMO' :xk00KKKK0Oxc'     ,lxO0KKKK0k;  cNMMMWKkc.  ,lxO0000Oxl:'    .oOOOd;;oxo''OWMMMWXklc::cod; .:xO00KKKK0Odc.    ;O000o;lxOl. .;ok00K0Ox;;0MMMWd.   .xMMMMMMMM")
    print("MMMMMMMWl      .dWMMWNWMMMk.  ,0MMMWWMMMWo.'0MMWWWWWWMMMMXl. 'kNMMMMWWWWWK; .xMMMMMMNc.;kNMMWNXXNMMMWXo.  :XMMMWNWMWxcOWMMMXo.          ,KMMWWWWWWMMMMKc  .xMMMMWWMMX:.;OWMMMMMMMMNXWMMMX:     lWMMMMMMM")
    print("MMMMMMMNc      '0MMMXkKMMMO' 'OMMMK0NMMMX; .:c:;,,,,:kWMMMX;.xWMMMNd;,,;;'  ,KMMMXd:,'oNMMW0c'..,kWMMMNl .dWMMMMWX0xcxWMMMX:            .:c:;,,,,:kWMMMK; ,KMMMMMN0xc.cXMMMMXklco0WMMMMMO.     cNMMMMMMM")
    print("MMMMMMMX:      cNMMMO:kMMMK,.kWMMKokWMMMk.    .,;:cccxNMMMNc.OMMMMNd,.      oWMMMk.  cNMMMXo,''',dNMMMMx.'0MMMMXo.  ;KMMMWd.              ..,;:ccckWMMMX: lWMMMWk,.  :XMMMWk,    ;KMMMMWo      :NMMMMMMM")
    print("MMMMMMMN:     .kMMMWo.dMMMXdkWMMXc;0MMMNl  ,oOXWWMMMMMMMMMK; cKWMMMWN0d:.  .OMMMNl  'OMMMMWWNNNWWWMMMMWd.cNMMMX:    cNMMMWl             ;d0XWWMMMMMMMMM0'.OMMMWk.   .OMMMMO'     'OMMMMK;      :NMMMMMMM")
    print("MMMMMMMNc     ;XMMMK, lWMMWNWMMNl.lNMMMK,.dNMMMXkoloOWMMMMk.  .:oONWMMMWK:.:NMMM0'  ;XMMMW0dddddddddddo'.kMMMWd.    :NMMMMk.          .xNMMWXkolo0WMMMWx.:XMMMK;    ;XMMMWo      lNMMMMk.      cNMMMMMMM")
    print("MMMMMMMWo     oWMMMx. :NMMMMMMNo..kMMMMx'dWMMMO,   .dWMMMNc       'lKMMMMO:xMMMMx.  '0MMMWo             ,KMMMK;     'OMMMMWk;.       .xWMMWk'   .xWMMMX:.dWMMMx.    ;KMMMM0;   .oXMMMMNl       oWMMMMMMM")
    print("MMMMMMMMk.   '0MMMNc  ;KMMMMMWd. ;XMMMN:'OMMMMO;..;dXMMMM0'.'......;OMMMMkc0MMMMKo:..lNMMMXd:,'',,,;;;. oWMMMk.      ;KMMMMMNKkxxkOc ,0MMMWk,.';xNMMMMO.'0MMMNc     .xWMMMMXOxkKWMMMMM0,      .kMMMMMMMM")
    print("MMMMMMMMK,   cNMMM0'  '0MMMMWx. .dWMMMO'.oNMMMMWXNWMMMMMWo.dNNXXXXXNMMMWO,.kMMMMMMWo .cKWMMMWWWNWWWWMK;.OMMMNl        'xXMMMMMMMMMMK;.dWMMMWNXNWMMMMMWl.cNMMM0'      .xWMMMMMMMMMMMMMWx.      ,KMMMMMMMM")
    print("MMMMMMMMWo  .oXXXXl   .xXXXXx.  .xXXXXl  .:x0XNXX0kOXXXXO,.o0KXXXXXXKOd:.  .o0XNXKk,   .:dOKXXXXXK0Okl.,0XXXO'          'cxOKXXXXKOx, .:xKXXXX0kOXXXXO'.oXXXXo.       .:xKXXKkod0XXXX0;       oWMMMMMMMM")
    print("MMMMMMMMM0'  .....     ......    .....      ......  .....   .........        .....         ........     .....               ......       ......  .....  ......           ....   ......       '0MMMMMMMMM")
    print("MMMMMMMMMWo                                                                                                                                                                                  oWMMMMMMMMM")
    print("MMMMMMMMMMK;                                                                     cOOOc.                          .cO0Ol.                                                                    ;KMMMMMMMMMM")
    print("MMMMMMMMMMMO'                                                                    ;KMMXc                          cXMMK;                                                                    'OMMMMMMMMMMM")
    print("MMMMMMMMMMMWx.                                                                    cNMMK;                        ;KMMNc                                                                    .xWMMMMMMMMMMM")
    print("MMMMMMMMMMMMWd.                                                                   .oNMM0,                      ,0MMNo.                                                                   .dWMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMWd.                                                                   .dNMM0,                    ;0MMNd.                                                                   .dWMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMWx.                                                                   .oNMMK:                  :KMMNo.                                                                   .kWMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMWO,                                                                   .lXMMXl.              .lXMMXl.                                                                   ,OWMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMXl.                                                                   :KMMNx'            'kWMM0:                                                                   .lXMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMWk,                                                                   'kWMWKc.        .lKMMNx'                                                                   ,kWMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMXo.                                                                  .lKMMWk;      ;OWMWKc.                                                                  .oXMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMWKl.                                                                  'xNMMNx,..,kNMMNd.                                                                  .lKWMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMWKl.                                                                  ;kNMMNKKNMMNk,                                                                  .lKWMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMWKd,                                                                 .dNMMMMMMNo.                                                                 ,dKWMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.                                                            .;xXWMMMMMMWKd,.                                                            .cONMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc'                                                      .;dKWMMMMMMMMMMMMN0o,.                                                      'ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;.                                              .,cxKWMMMMMMMMMMMMMMMMMMW0d:'.                                              .;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:'.                                     .;lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc,.                                     .':okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkoc;'..                       ..,:ox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,..                       ..';cokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxdolc::;;;;;;;:cclodkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkdolcc:;;;;;;;::clodxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")



def elo_cartao():
    print(".............................,:clooddxxxddollc;,........................................................................................................................................................")
    print("..........................;OKNWMMMMMMMMMMMMMMMWNKOxo:,..................................................................................................................................................")
    print("......................... 'OMMMMMMMMMMMMMMMMMMMMMMMMWX0dc'..............................................................................................................................................")
    print("...........................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,...........................................................................................................................................")
    print("............................oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc.........................................................................................................................................")
    print("...........,dx:............ 'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.......................................................................cxxxxxxxxl. ....................................................")
    print(".........'dXMMNx,............;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l................................................................... .OMMMMMMMM0, ....................................................")
    print("........cKWMMMMMXd'...........oNMMMWNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMWO;................................................................. .OMMMMMMMM0, ....................................................")
    print("......'xNMMMMMMMMMKl......... .loc:;;,,,;:clok0NWMMMMMMMMMMMMMMMMMMMXo................................................................ .OMMMMMMMM0, ....................................................")
    print(".....;0WMMMMMMMMMMMW0:..........  ........   ..,cd0WMMMMMMMMMMMMMMMMMWk'................................ .......   ................... .OMMMMMMMM0, .......................  .......  ..................")
    print("....:KMMMMMMMMMMMMMMMNk'...........................:xXMMMMMMMMMMMMMMMMWO,...........................',:lodxkkkkxdol:,................. .OMMMMMMMM0, .....................,codxkkkkxdolc;................")
    print("...:KMMMMMMMMMMMMMMMWKl..............................,dXMMMMMMMMMMMMMMMMO,......................:okKXNMMMMMMMMMMMMMWNKko;............. .OMMMMMMMM0, .....................oWMMMMMMMMMMMMNKOd:'...........")
    print(". ,0MMMMMMMMMMMMMMMNd'.................................;kWMMMMMMMMMMMMMMWk...................;dKWMMMMMMMMMMMMMMMMMMMMMMMW0d;.......... .OMMMMMMMM0, .................... 'OMMMMMMMMMMMMMMMMWXx:.........")
    print("..xWMMMMMMMMMMMMMMXc.....................................dNMMMMMMMMMMMMMMNl................;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc........ .OMMMMMMMM0, ...........,do,.......:XMMMMMMMMMMMMMMMMMMW0l.......")
    print(".cXMMMMMMMMMMMMMMX:.......................................oNMMMMMMMMMMMMMM0, ............'xNMMMMMMMMMMMMMMWNNNNWMMMMMMMMMMMMMNk;...... .OMMMMMMMM0, .........'dXMMKo.......dWMMMMMMMMMMMMMMMMMMMW0c.....")
    print(".kMMMMMMMMMMMMMMNl....................................... .xWMMMMMMWNXKOkxl'............;0WMMMMMMMMMMWKkoc:,,,,:ld0NMMMMMMMMMMMXl..... .OMMMMMMMM0, ........;0WMMMMW0c.... 'dkdoodxk0NWMMMMMMMMMMMNx'...")
    print(",KMMMMMMMMMMMMMMk. ....................................... ,k0kxolc:,'.... ............:XMMMMMMMMMNkl:.. ..........;xXMMMMMMMMMMNo.... .OMMMMMMMM0, .......:KMMMMMMMMWO:......    ...,cxXMMMMMMMMMMWk'..")
    print("cNMMMMMMMMMMMMMNl...............................................  ....................;KMMMMMMMMWO;. .............':dKMMMMMMMMMMMNo... .OMMMMMMMM0, ......;KMMMMMMMMMW0:................'dXMMMMMMMMMWk..")
    print("lWMMMMMMMMMMMMMX: .................................................................. .kMMMMMMMMWk'...........';lx0XWMMMMMMMMMMMMWNk'.. .OMMMMMMMM0, .... .kMMMMMMMMMWx'...................;0WMMMMMMMMNo.")
    print("oWMMMMMMMMMMMMMX; ...................................................................cNMMMMMMMMK; .... ..,cdOXWMMMMMMMMMMMMMWKkoc,.... .OMMMMMMMM0, .....cNMMMMMMMMWx......................,0MMWNXKOkd:.")
    print("lNMMMMMMMMMMMMMNc ........................................... .......................dMMMMMMMMMk. .';:okKNMMMMMMMMMMMMMWX0xl;.. ...... .OMMMMMMMM0, .....xMMMMMMMMMK; ......................;lc:,'......")
    print(";XMMMMMMMMMMMMMWx. .........................................clc:;'....  ........... .xMMMMMMMMM0ox0XWWMMMMMMMMMMMMMNKko:,............. .OMMMMMMMM0, ... .kMMMMMMMMMO. ..................................")
    print("'OMMMMMMMMMMMMMMK:.........................................lNMMWNXK0kxolc:,..........xMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;.................. .OMMMMMMMM0, ... .xMMMMMMMMMO' ..........................   .....")
    print(".oWMMMMMMMMMMMMMMO'.......................................:KMMMMMMMMMMMMMW0; ........lWMMMMMMMMMMMMMMMMMMWN0xl:'...................... .OMMMMMMMM0, .....oWMMMMMMMMNc.......................o0Oxdol:;'..")
    print(".'OMMMMMMMMMMMMMMWO,.....................................:KMMMMMMMMMMMMMMWx......... ,0MMMMMMMMMMMMMMWKkoc,........................... .OMMMMMMMM0, .... ;KMMMMMMMMMK;.....................oNMMMMMMWWXo.")
    print("..cXMMMMMMMMMMMMMMW0:...................................lXMMMMMMMMMMMMMMM0,...........lNMMMMMMMWXOxl:;.................co;............ .OMMMMMMMM0, ......oWMMMMMMMMMKl..................'xNMMMMMMMMMK;.")
    print("...oNMMMMMMMMMMMMMMMNx,...............................;kWMMMMMMMMMMMMMMMX:.............oNMWNKko:'.. ................'cOWMNOo;......... .OMMMMMMMM0, ..... .xWMMMMMMMMMXl............. .,oKWMMMMMMMMMXc..")
    print("....dNMMMMMMMMMMMMMMMMO,............................:kNMMMMMMMMMMMMMMMMXc...............cdc,.. .....;okl;.......';lkXWMMMMMMNOo;...... .kMMMMMMMMNxc,.......xNMMMMMMW0:.....,;,''',;cdONMMMMMMMMMMMXc...")
    print(".....oNMMMMMMMMMMMMMNx,..........................;o0WMMMMMMMMMMMMMMMMMKc..........................,ONWMMWK0OkOO0XWMMMMMMMMMMMMWx........dWMMMMMMMMMMNKko;....lKMMMWKl......:XWNXXXNWMMMMMMMMMMMMMWO;....")
    print("......cKMMMMMMMMMMWO:..........,,'.........';cokKWMMMMMMMMMMMMMMMMMMWO;..........................cKMMMMMMMMMMMMMMMMMMMMMMMMMW0c........ ,0MMMMMMMMMMMMMX:.....,xXXd'..... 'OMMMMMMMMMMMMMMMMMMMWKl......")
    print(".......,kWMMMMMMW0c...........:XNXK0OOkOO0KXWMMMMMMMMMMMMMMMMMMMMMMNd...........................dNMMMMMMMMMMMMMMMMMMMMMMMMNkc............,xNMMMMMMMMMMXl........,'........dWMMMMMMMMMMMMMMMMMNOl'.......")
    print(".........c0WMMMXo........... 'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;...........................'o0NMMMMMMMMMMMMMMMMMMMWXkl,................,okKNMMMMMNo..................cXMMMMMMMMMMMMMMWXOo;..........")
    print("...........l0Xx,.............dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:................................,clok0KXNWWWWWNX0Odl:'.......................;cdOKNd................. .l0XNWWWMWWNXKOxoc,.............")
    print(".............'..............cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:....................................  ...,;;:::;,'............................... .',.......................,;::::;;'... ...............")
    print(".......................... 'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,..........................................................................................................................................")
    print("......................... .dWMMMMMMMMMMMMMMMMMMMMMMMMMWKkl,.............................................................................................................................................")
    print("..........................:XMMMMMMMMMMMMMMMMMMMMMWX0xl;.................................................................................................................................................")
    print("...........................;codkO0KKKXXXKK00Oxdlc;'.. ..................................................................................................................................................")
    print("............................   ....'',,,''....  ........................................................................................................................................................")



def sair():
    print("__________________¶¶¶¶¶                      ")
    print("_______________¶¶¶¶¶__¶¶________¶¶¶¶¶¶¶¶")
    print("__________¶¶¶¶__¶¶¶¶___¶¶_____¶¶¶¶¶____¶¶")
    print("______¶¶¶___¶¶¶¶________¶¶_¶¶¶______¶¶¶")
    print("___¶¶¶_¶¶¶¶______________¶¶_______¶¶¶")
    print("¶¶¶_¶¶¶¶________________¶¶______¶¶¶")
    print("¶¶¶¶_________________¶¶¶_____¶¶¶")
    print("¶¶________________¶¶¶_____¶¶¶")
    print("¶¶_____________¶¶¶_____¶¶¶")
    print("_¶¶________¶¶¶¶____¶¶¶¶")
    print("__¶¶____¶¶¶_____¶¶¶¶")
    print("___¶¶_¶¶¶¶___¶¶¶¶")
    print("____¶¶_____¶¶¶¶")
    print("__¶¶_____¶¶¶¶")
    print("¶¶____¶¶¶¶")
    print("¶¶_¶¶¶¶")
    print("¶¶¶¶¶_____¶¶¶¶¶___________¶¶¶¶¶")
    print("_________¶¶¶¶¶¶¶_________¶¶¶¶¶¶¶")
    print("_________¶¶¶¶¶¶¶_________¶¶¶¶¶¶¶")
    print("__________¶¶¶¶¶___________¶¶¶¶¶")
    print("__¶¶¶¶_____________________________¶¶¶¶")
    print("_¶¶¶¶¶¶___________________________¶¶¶¶¶")
    print("__¶¶¶¶¶¶_________________________¶¶¶¶¶¶")
    print("___¶¶¶¶¶¶_______________________¶¶¶¶¶¶")
    print("____¶¶¶¶¶¶¶___________________¶¶¶¶¶¶¶")
    print("______¶¶¶¶¶¶¶_______________¶¶¶¶¶¶¶")
    print("_________¶¶¶¶¶¶___________¶¶¶¶¶¶")
    print("____________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
    print("______________¶¶¶¶¶¶¶¶¶¶¶¶")
    sys.exit()
	